version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: install python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install twine
      - run:
          name: verify git tag vs. version
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python3 setup.py verify
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = amogh" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: create packages
          command: |
            python3 setup.py sdist
            python3 setup.py bdist_wheel
      - run:
          name: run unit tests
          command: | 
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements.txt
            pytest rsHRF/unit_tests/ -p no:warnings
      - run:
          name: upload to pypi
          command: |
            . venv/bin/activate
            twine upload dist/* 
      - run:
          name: run integration test
          command: | 
            python3 -m venv venv
            . venv/bin/activate
            pip3 install rshrf
            mkdir ${HOME}/scratch 
            mkdir ${HOME}/scratch/downloads
            wget -c -P ${HOME}/scratch/downloads/ "https://osf.io/xv72t//download"
            tar xf ${HOME}/scratch/downloads/download -C ${HOME}/scratch
            rsHRF --bids_dir ${HOME}/scratch/ds002790/derivatives/fmriprep/ --output_dir ${HOME}/scratch/ds002790 --participant_label 0001 --brainmask --estimation canon2dd --analysis_level participant
          no_output_timeout: 6h
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            sudo mv /tmp/docker/* /usr/bin
      - run:
          name: Build Docker image
          command: |
            docker build -t "bids/${CIRCLE_PROJECT_REPONAME,,}" .
      - run:
          name: push to dockerhub
          command: |
            wget https://raw.githubusercontent.com/bids-apps/maintenance-tools/main/circleci/push_docker.sh
            bash push_docker.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          context:
          - dockerhub
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              only:
                -master

# VS Code Extension Version: 1.5.1
